### ISSUE TITLE
Datastore Emulator returns an error code of UNKNOWN when committing a transaction

### ISSUE THREAD

**Issue by hach-que** [googleapis/google-cloud-datastore#201]
Seeing this in the logs of the Datastore emulator:

```
[datastore] SEVERE: Exception while executing runnable io.grpc.internal.ServerImpl$JumpToApplicationThreadServerStreamListener$1HalfClosed@37c19d8
[datastore] com.google.common.util.concurrent.UncheckedExecutionException: com.google.cloud.datastore.core.exception.DatastoreException: too much contention on these datastore entities. please try again.
[datastore]     at com.google.common.cache.LocalCache$LocalLoadingCache.getUnchecked(LocalCache.java:4816)
[datastore]     at com.google.cloud.datastore.emulator.impl.CloudDatastoreV1$ExistenceCache.exists(CloudDatastoreV1.java:331)
[datastore]     at com.google.cloud.datastore.emulator.impl.CloudDatastoreV1.applyMutation(CloudDatastoreV1.java:750)[datastore]     at com.google.cloud.datastore.emulator.impl.CloudDatastoreV1.applyMutationList(CloudDatastoreV1.java:693)
[datastore]     at com.google.cloud.datastore.emulator.impl.CloudDatastoreV1.commit(CloudDatastoreV1.java:374)
[datastore]     at com.google.cloud.datastore.emulator.v1.DatastoreV1Emulator.commit(DatastoreV1Emulator.java:132)
[datastore]     at com.google.cloud.datastore.emulator.v1.DatastoreEmulatorGrpcAdapter$1.commit(DatastoreEmulatorGrpcAdapter.java:155)
[datastore]     at com.google.datastore.v1.DatastoreGrpc$MethodHandlers.invoke(DatastoreGrpc.java:861)
[datastore]     at io.grpc.stub.ServerCalls$UnaryServerCallHandler$UnaryServerCallListener.onHalfClose(ServerCalls.java:171)
[datastore]     at io.grpc.internal.ServerCallImpl$ServerStreamListenerImpl.halfClosed(ServerCallImpl.java:272)
[datastore]     at io.grpc.internal.ServerImpl$JumpToApplicationThreadServerStreamListener$1HalfClosed.runInContext(ServerImpl.java:650)
[datastore]     at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37)
[datastore]     at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:123)
[datastore]     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1152)
[datastore]     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:622)
[datastore]     at java.lang.Thread.run(Thread.java:748)
[datastore] Caused by: com.google.cloud.datastore.core.exception.DatastoreException: too much contention on these datastore entities. please try again.
[datastore]     at com.google.cloud.datastore.emulator.impl.Utils.newError(Utils.java:75)
[datastore]     at com.google.cloud.datastore.emulator.impl.Utils.newError(Utils.java:79)
[datastore]     at com.google.cloud.datastore.emulator.impl.BaseLocalDatastore$EntityGroupTracker.checkEntityGroupVersion(BaseLocalDatastore.java:2220)
[datastore]     at com.google.cloud.datastore.emulator.impl.BaseLocalDatastore$LiveTxn.trackEntityGroup(BaseLocalDatastore.java:2121)
[datastore]     at com.google.cloud.datastore.emulator.impl.BaseLocalDatastore$Profile$EntityGroup.addTransaction(BaseLocalDatastore.java:1304)
[datastore]     at com.google.cloud.datastore.emulator.impl.BaseLocalDatastore.get(BaseLocalDatastore.java:507)
[datastore]     at com.google.cloud.datastore.emulator.impl.CloudDatastoreV1$ExistenceCache$1.load(CloudDatastoreV1.java:311)
[datastore]     at com.google.cloud.datastore.emulator.impl.CloudDatastoreV1$ExistenceCache$1.load(CloudDatastoreV1.java:306)
[datastore]     at com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3453)
[datastore]     at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2170)
[datastore]     at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2129)
[datastore]     at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2042)
[datastore]     at com.google.common.cache.LocalCache.get(LocalCache.java:3879)
[datastore]     at com.google.common.cache.LocalCache.getOrLoad(LocalCache.java:3883)
[datastore]     at com.google.common.cache.LocalCache$LocalLoadingCache.get(LocalCache.java:4808)
[datastore]     at com.google.common.cache.LocalCache$LocalLoadingCache.getUnchecked(LocalCache.java:4814)
[datastore]     ... 15 more
[datastore]
```

Looks like the internal "too much contention" error is not being correctly propagating to the client. However it should be noted that we see this error consistently all the time, even when the application is using exponential back-off.

**Comment by evanj** [comment]
In case this repo is not being maintained, I filed this in the GCP issue tracker: https://issuetracker.google.com/issues/119520139

**Comment by mneumiller** [comment]
It looks like the emulator is returning the wrong code when it fails on a commit for creating due to contention. The code snippet is from datastore/transaction.go in the Commit() func. 
```	
resp, err := t.client.client.Commit(t.ctx, req)
if grpc.Code(err) == codes.Aborted {
	return nil, ErrConcurrentTransaction
}
t.id = nil // mark the transaction as expired
if err != nil {
	return nil, err
}
```

**Comment by hermanbanken** [comment]
Issue tracker (https://issuetracker.google.com/issues/119520139) marked it as resolved. Close this too?

**Comment by meredithslota** [comment]
Closing as linked issue is fixed. Thanks!
